version: '3.8'
services:
  web:
    build:
      context: .
    volumes:
      - .:/app
    #command: npm run start:dev
    ports:
      - "10000:10000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
